name    'abiquo-anycloud'
version '0.1.0'
source 'UNKNOWN'
author 'abiquo'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'jfryman/nginx', '>= 0.0.9'
dependency 'camptocamp/openssl', '>= 0.3.1'
dependency 'maestrodev/rvm', '>= 1.4.1'
dependency 'spiette/selinux', '>= 0.5.4'
dependency 'puppetlabs/firewall', '>= 1.0.0'